### ISSUE TITLE
Using go_router to handle routing in the app.

### ISSUE THREAD

**Issue by thisisamank** [vedantbahel/viteED#15]
Using go_router to handle routing in the app will give us a lot of features for routing with no complexity. [go_router](https://pub.dev/packages/go_router)

**Comment by cupcake08** [comment]
Agree with that

**Comment by cupcake08** [comment]
I suggest to use [GetX](https://pub.dev/packages/get) for this project as we can get both State management and Routing Mechanism from a single package instead of using another package
