### ISSUE TITLE
Decide a State Management

### ISSUE THREAD

**Issue by WilfredAlmeida** [vedantbahel/viteED#2]
Decide a state management package, developers have their preferences. Needs to be decided before conrtibutions begin.

I'd suggest the GetX State Management since:
 - It's easy to implement
 - Initializes controllers only once
 - Doesn't need context
 - In case of reinitialization of a controller, it'll check if there is any instance created and simply return it
 - It comes with other features like Storage, Navigation, Dialog, Snackbar, Network Calls etc.

**Comment by SirusCodes** [comment]
I would disagree with using GetX
It has a lot of things inbuilt but it comes at a cost. Cost of maintaining it. It has a huge API surface and what if one day the dev decides stop maintaining it. Then you have to not only migrate state management but also all the other things like navigation and dialogs and what not.

Also GetX acts like a whole new framework upon flutter.

I would suggest using BLoC or Provider/Riverpod as they are battle tested and does one thing right that is state management.

**Comment by moshOntong-IT** [comment]
Using very_good_cli is preferable. It use bloc state management.

**Comment by moshOntong-IT** [comment]
> Using very_good_cli is preferable. It use bloc state management. 

Please read the very_good_cli

**Comment by annurdien** [comment]
I'd suggest Riverpod

**Comment by vedantbahel** [comment]
Checked out this appwrite_flutter template https://github.com/lohanidamodar/flutter_appwrite_starter
the person uses Riverpod for state management. This looks good to add.

**Comment by AftabBagwan** [comment]
I'd suggest Riverpod too.

**Comment by SirusCodes** [comment]
I honestly cannot contribute with code rn as I already have a lot on my plate. I can help with issues and PR reviews.

We can do a project as features. Similar to what it gives with the skeleton example app

**Comment by DonnC** [comment]
Riverpod in my case
From demador who is also among the core appwrite team and his examples on flutter he also uses riverpod, not that he forcefully suggests it but i also go with riverpod here in the long run
GetX has mixed acceptance.

**Comment by Odinachi** [comment]
I would have loved to use cubit but it seems Riverpod will have it, in that case, that's cool too. so yes Riverpod.
