### ISSUE TITLE
Interests tag user-input while sign up

### ISSUE THREAD

**Issue by vedantbahel** [vedantbahel/viteED#25]
the app should show mini-blogs in the domain that interests user. thus, it is important that we collect that information. 
Add an option in the sign up form to multi-select following predefined tags. It should be tap and select based system. 

Domain(s): Software Engineering, Web Dev, Mobile App Dev, Product Designing, Machine Learning, Cyber Security

As of now, we will keep the domains limited for the initial version of the project.

**Comment by ShivamMenda** [comment]
@vedantbahel Can I take up this feature and work on it on the weekend?

**Comment by vedantbahel** [comment]
Done!
Good luck and thank you!

**Comment by ShivamMenda** [comment]
@vedantbahel Thanks!

**Comment by vedantbahel** [comment]
Please add one more feature. The user must select at least 3 domains to continue.

**Comment by ShivamMenda** [comment]
@vedantbahel I have implemented the feature with validation using the multi_select package. I have opened a PR on this please do check it out and let me know if any changes are required.
